### ISSUE TITLE
Query about updating for NudeNet and GIPHY Celebrity Detector

### ISSUE THREAD

**Issue by SLU010** [clear-nus/selective-amnesia#1]
Hi, thanks for your awesome and interesting work! 

I was wondering if there have been any updates regarding the release of the code for using NudeNet and GIPHY Celebrity Detector under the 'sd' folder. I'm keen on exploring these tools.

**Comment by ajrheng** [comment]
Hi, apologies for the late reply. Will work to get them up hopefully by this week.

**Comment by ajrheng** [comment]
I've pushed an update with NudeNet and GIPHY Celebrity Detector as well as instructions in the readme. Note that the dependencies in `environment.yaml` has changed. NudeNet should work fine. 

I'm having issues reinstalling GCD and running into [package versioning hell](https://github.com/Giphy/celeb-detection-oss/issues/14). I don't recall how I did it the first time around... Regardless, you should try installing it using the official instructions and see if you have any luck. There are two files that I modified to work with my experiments which you just have to replace; I've provided them in the latest commit. Hope this works, and let me know if you are able to install GCD correctly.

**Comment by SLU010** [comment]
Thanks for your kind help! Will have a try.
