### ISSUE TITLE
Is there any pretrained weight for SA nudity experiment?

### ISSUE THREAD

**Issue by enkeejunior1** [clear-nus/selective-amnesia#3]
Thank you for your awesome work. 

If you can provide the weight after SA, it will greatly help for reproduce. Thank you in advance.

**Comment by ajrheng** [comment]
Hi, thanks for the interest in our work. The weights are already released here https://huggingface.co/ajrheng/selective-amnesia/tree/main. You can find the nudity weights under `nudity.ckpt`.
